server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
      base-path: "/actuator"
spring:
  application:
    name: PricesJavaTest
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:h2:mem:PricesJavaTest
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
