server:
  port: 7001

spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  application:
    name: PricesJavaTest
  datasource:
    url: jdbc:h2:mem:PricesJavaTest
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
