openapi: 3.0.0
info:
  title: priceApis
  version: '1.0'
servers:
  - url: 'http://localhost:8080'

paths:
  /price:
    $ref: 'paths/prices/price-by-parameters.yml'

components:
  schemas:
    PriceResponse:
      $ref: 'schemas/price/PriceResponse.yml#/PriceResponse'